=== CloudEngineHub/penrose/packages/core/src/types/trio-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "title": "Penrose Trio",
  "description": "An example in Penrose consisting of a substance, style, and domain program, as well as additional information",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Human-readable name of the trio"
    },
    "substance": {
      "$ref": "#/$defs/program"
    },
    "style": {
      "$ref": "#/$defs/program"
    },
    "domain": {
      "$ref": "#/$defs/program"
    },
    "variation": {
      "type": "string",
      "description": "Variation seed for the trio"
    }
  },
  "required": ["name", "substance", "style", "domain", "variation"],
  "$defs": {
    "program": {
      "description": "A Penrose program",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Human-readable name of the program"
        },
        "path": {
          "type": "string",
          "description": "Relative path from trio file to the program"
        }
      },
      "required": ["name", "path"]
    }
  }
}

=== CloudEngineHub/penrose/packages/examples/src/lagrange-bases/trio-lagrange-bases-lagrange-bases.json
{
  "name": "Lagrange Bases / Lagrange Bases / Lagrange Bases",
  "variation": "RainmakerMarten88256",
  "substance": {
    "name": "Lagrange Bases",
    "path": "example.sub"
  },
  "style": {
    "name": "Lagrange Bases",
    "path": "lagrange-bases.sty"
  },
  "domain": {
    "name": "Lagrange Bases",
    "path": "lagrange-bases.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/geometry-domain/textbook_problems/trio-incenter-triangle-euclidean.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Triangle with Incenter and Right Angle Marker / Euclidean 2D Geometry / Geometry",
  "variation": "",
  "substance": {
    "name": "Triangle with Incenter and Right Angle Marker",
    "path": "c05p13.sub"
  },
  "style": {
    "name": "Euclidean 2D Geometry",
    "path": "euclidean.sty"
  },
  "domain": {
    "name": "Geometry",
    "path": "geometry.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/set-theory-domain/trio-continuousmap-continuousmap.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Continuous Map / Continuous Map / Functions",
  "variation": "",
  "substance": {
    "name": "Continuous Map",
    "path": "continuousmap.sub"
  },
  "style": {
    "name": "Continuous Map",
    "path": "continuousmap.sty"
  },
  "domain": {
    "name": "Functions",
    "path": "functions.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/shape-distance/trio-points-around-line-shape-distance.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Points around a Line / Sign Distance Functions / Signed Distance Function",
  "variation": "GalapagosLocust418",
  "substance": {
    "name": "Points around a Line",
    "path": "hundred-points-around-line.sub"
  },
  "style": {
    "name": "Sign Distance Functions",
    "path": "shape-distance.sty"
  },
  "domain": {
    "name": "Signed Distance Function",
    "path": "shapes.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/minkowski-tests/maze/trio-non-convex-non-convex.json
{
  "name": "Non-convex Shape / Non-convex Shape / Non-convex Shape",
  "variation": "",
  "substance": {
    "name": "Non-convex Shape",
    "path": "maze.sub"
  },
  "style": {
    "name": "Non-convex Shape",
    "path": "maze.sty"
  },
  "domain": {
    "name": "Non-convex Shape",
    "path": "maze.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/geometry-domain/textbook_problems/trio-parallel-lines-euclidean.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Parallel Lines with Marker / Euclidean 2D Geometry / Geometry",
  "variation": "SuluHippopotamus665",
  "substance": {
    "name": "Parallel Lines with Marker",
    "path": "c03p01.sub"
  },
  "style": {
    "name": "Euclidean 2D Geometry",
    "path": "euclidean.sty"
  },
  "domain": {
    "name": "Geometry",
    "path": "geometry.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/exterior-algebra/trio-vector-wedge-exterior-algebra.json
{
  "name": "Wedge product of three Vectors / Operations on k-vectors from exterior algebra / Exterior Algebra",
  "variation": "ArtemisCrane740",
  "substance": {
    "name": "Wedge product of three Vectors",
    "path": "vector-wedge.sub"
  },
  "style": {
    "name": "Operations on k-vectors from exterior algebra",
    "path": "exterior-algebra.sty"
  },
  "domain": {
    "name": "Exterior Algebra",
    "path": "exterior-algebra.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/atoms-and-bonds/trio-one-water-molecule-atoms-and-bonds.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "One water molecule drawn using symmetric bonds / atoms-and-bonds / Atoms and Bonds",
  "variation": "PorcellanaFlamingo3169",
  "substance": {
    "name": "One water molecule drawn using symmetric bonds",
    "path": "one-water-molecule.sub"
  },
  "style": {
    "name": "atoms-and-bonds",
    "path": "atoms-and-bonds.sty"
  },
  "domain": {
    "name": "Atoms and Bonds",
    "path": "atoms-and-bonds.dsl"
  }
}
