=== CloudEngineHub/penrose/packages/core/src/types/trio-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "title": "Penrose Trio",
  "description": "An example in Penrose consisting of a substance, style, and domain program, as well as additional information",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Human-readable name of the trio"
    },
    "substance": {
      "$ref": "#/$defs/program"
    },
    "style": {
      "$ref": "#/$defs/program"
    },
    "domain": {
      "$ref": "#/$defs/program"
    },
    "variation": {
      "type": "string",
      "description": "Variation seed for the trio"
    }
  },
  "required": ["name", "substance", "style", "domain", "variation"],
  "$defs": {
    "program": {
      "description": "A Penrose program",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Human-readable name of the program"
        },
        "path": {
          "type": "string",
          "description": "Relative path from trio file to the program"
        }
      },
      "required": ["name", "path"]
    }
  }
}

=== CloudEngineHub/penrose/packages/examples/src/graph-domain/trio-small-graph-disjoint-rects.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Small graph / Disjoint rectangles in box / Graph Theory",
  "variation": "",
  "substance": {
    "name": "Small graph",
    "path": "small-graph.sub"
  },
  "style": {
    "name": "Disjoint rectangles in box",
    "path": "disjoint-rects.sty"
  },
  "domain": {
    "name": "Graph Theory",
    "path": "graph-theory.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/linear-algebra-domain/trio-two-vectors-perp-vectors-dashed.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Two Perpendicular Vectors / Vectors with Dashed Arrows / Linear Algebra",
  "variation": "",
  "substance": {
    "name": "Two Perpendicular Vectors",
    "path": "twoVectorsPerp-unsugared.sub"
  },
  "style": {
    "name": "Vectors with Dashed Arrows",
    "path": "linearalgebra-paper-dashes.sty"
  },
  "domain": {
    "name": "Linear Algebra",
    "path": "linear-algebra.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/geometry-domain/textbook_problems/trio-midsegment-triangles-euclidean.json
{
  "name": "Nested Triangles with Incenters / Euclidean 2D Geometry / Geometry",
  "variation": "FollyCamel2864",
  "substance": {
    "name": "Nested Triangles with Incenters",
    "path": "c05p01.sub"
  },
  "style": {
    "name": "Euclidean 2D Geometry",
    "path": "euclidean.sty"
  },
  "domain": {
    "name": "Geometry",
    "path": "geometry.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/set-theory-domain/trio-tree-venn-3d.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Tree / Venn 3D / Set Theory",
  "variation": "",
  "substance": {
    "name": "Tree",
    "path": "tree.sub"
  },
  "style": {
    "name": "Venn 3D",
    "path": "venn-3d.sty"
  },
  "domain": {
    "name": "Set Theory",
    "path": "setTheory.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/graph-domain/trio-small-graph-disjoint-rects-large-canvas.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Small graph / Disjoint rectangles in a large box / Graph Theory",
  "variation": "",
  "substance": {
    "name": "Small graph",
    "path": "small-graph.sub"
  },
  "style": {
    "name": "Disjoint rectangles in a large box",
    "path": "disjoint-rects-large-canvas.sty"
  },
  "domain": {
    "name": "Graph Theory",
    "path": "graph-theory.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/walk-on-spheres/trio-wos-laplace-estimator-walk-on-spheres.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "WoS Laplace Estimator / Walk on Spheres / Walk on Spheres",
  "variation": "RainmakerMarten88256",
  "substance": {
    "name": "WoS Laplace Estimator",
    "path": "Laplace.sub"
  },
  "style": {
    "name": "Walk on Spheres",
    "path": "walk-on-spheres.sty"
  },
  "domain": {
    "name": "Walk on Spheres",
    "path": "walk-on-spheres.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/geometry-domain/trio-siggraph-teaser-euclidean-teaser.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "SIGGRAPH teaser / Euclidean - SIGGRAPH teaser / Geometry",
  "variation": "StromboliCat61816",
  "substance": {
    "name": "SIGGRAPH teaser",
    "path": "teaser.sub"
  },
  "style": {
    "name": "Euclidean - SIGGRAPH teaser",
    "path": "euclidean-teaser.sty"
  },
  "domain": {
    "name": "Geometry",
    "path": "geometry.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/graph-domain/trio-small-graph-disjoint-rect-line-horiz.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Small graph / Disjoint rectangles and lines in box / Graph Theory",
  "variation": "BriocheChamois5430",
  "substance": {
    "name": "Small graph",
    "path": "small-graph.sub"
  },
  "style": {
    "name": "Disjoint rectangles and lines in box",
    "path": "disjoint-rect-line-horiz.sty"
  },
  "domain": {
    "name": "Graph Theory",
    "path": "graph-theory.dsl"
  }
}
