=== CloudEngineHub/penrose/packages/core/src/types/trio-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "title": "Penrose Trio",
  "description": "An example in Penrose consisting of a substance, style, and domain program, as well as additional information",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Human-readable name of the trio"
    },
    "substance": {
      "$ref": "#/$defs/program"
    },
    "style": {
      "$ref": "#/$defs/program"
    },
    "domain": {
      "$ref": "#/$defs/program"
    },
    "variation": {
      "type": "string",
      "description": "Variation seed for the trio"
    }
  },
  "required": ["name", "substance", "style", "domain", "variation"],
  "$defs": {
    "program": {
      "description": "A Penrose program",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Human-readable name of the program"
        },
        "path": {
          "type": "string",
          "description": "Relative path from trio file to the program"
        }
      },
      "required": ["name", "path"]
    }
  }
}

=== CloudEngineHub/penrose/packages/examples/src/geometry-domain/textbook_problems/trio-circle-example-euclidean.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Circle with Chords, Radii, Diameters / Euclidean 2D Geometry / Geometry",
  "variation": "ShiitakeEchidna6061",
  "substance": {
    "name": "Circle with Chords, Radii, Diameters",
    "path": "c11p12.sub"
  },
  "style": {
    "name": "Euclidean 2D Geometry",
    "path": "euclidean.sty"
  },
  "domain": {
    "name": "Geometry",
    "path": "geometry.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/walk-on-spheres/trio-wos-nested-estimator-walk-on-spheres.json
{
  "name": "WoS Laplace Estimator / Walk on Spheres / Walk on Spheres",
  "variation": "WhiteoutSnail17459",
  "substance": {
    "name": "WoS Laplace Estimator",
    "path": "Nested.sub"
  },
  "style": {
    "name": "Walk on Spheres",
    "path": "walk-on-spheres.sty"
  },
  "domain": {
    "name": "Walk on Spheres",
    "path": "walk-on-spheres.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/shape-distance/trio-points-around-polyline-shape-distance.json
{
  "name": "Points around a Polyline / Sign Distance Functions / Signed Distance Function",
  "variation": "SharkskinWalrus24396",
  "substance": {
    "name": "Points around a Polyline",
    "path": "ninety-points-around-polyline.sub"
  },
  "style": {
    "name": "Sign Distance Functions",
    "path": "shape-distance.sty"
  },
  "domain": {
    "name": "Signed Distance Function",
    "path": "shapes.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/atoms-and-bonds/trio-wet-floor-atoms-and-bonds.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "Three Water Molecules drawn using strong and weak bonds, using symmetry and aliasing / atoms-and-bonds / Atoms and Bonds",
  "variation": "SinisterPigeon34750",
  "substance": {
    "name": "Three Water Molecules drawn using strong and weak bonds, using symmetry and aliasing",
    "path": "wet-floor.sub"
  },
  "style": {
    "name": "atoms-and-bonds",
    "path": "atoms-and-bonds.sty"
  },
  "domain": {
    "name": "Atoms and Bonds",
    "path": "atoms-and-bonds.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/walk-on-spheres/trio-wos-poisson-estimator-walk-on-spheres.json
{
  "$schema": "https://raw.githubusercontent.com/penrose/penrose/main/packages/core/src/types/trio-schema.json",
  "name": "WoS Laplace Estimator / Walk on Spheres / Walk on Spheres",
  "variation": "TideHawk3699",
  "substance": {
    "name": "WoS Laplace Estimator",
    "path": "Poisson.sub"
  },
  "style": {
    "name": "Walk on Spheres",
    "path": "walk-on-spheres.sty"
  },
  "domain": {
    "name": "Walk on Spheres",
    "path": "walk-on-spheres.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/geometry-domain/textbook_problems/trio-congruent-triangles-euclidean.json
{
  "name": "Congruent Triangles with Markers / Euclidean 2D Geometry / Geometry",
  "variation": "OspreySkunk922",
  "substance": {
    "name": "Congruent Triangles with Markers",
    "path": "ex.sub"
  },
  "style": {
    "name": "Euclidean 2D Geometry",
    "path": "euclidean.sty"
  },
  "domain": {
    "name": "Geometry",
    "path": "geometry.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/hypergraph/trio-hypergraph-hypergraph.json
{
  "name": "Hypergraph / Hypergraph / Hypergraph",
  "variation": "ConceptualMeerkat694",
  "substance": {
    "name": "Hypergraph",
    "path": "hypergraph.sub"
  },
  "style": {
    "name": "Hypergraph",
    "path": "hypergraph.sty"
  },
  "domain": {
    "name": "Hypergraph",
    "path": "hypergraph.dsl"
  }
}

=== CloudEngineHub/penrose/packages/examples/src/fake-3d-linear-algebra/trio-3d-projection-fake-3d-linear-algebra.json
{
  "name": "Projection onto Subspace and its Orthogonal Complement / Fake 3d Linear Algebra / Fake 3d Linear Algebra",
  "variation": "ConceptualMeerkat694",
  "substance": {
    "name": "Projection onto Subspace and its Orthogonal Complement",
    "path": "projection.sub"
  },
  "style": {
    "name": "Fake 3d Linear Algebra",
    "path": "fake3d.sty"
  },
  "domain": {
    "name": "Fake 3d Linear Algebra",
    "path": "fake3d.dsl"
  }
}
